### PR TITLE
Ignore interaction enabled flag if explicit timeout given

### PR DESCRIPTION
**Pull request by mattremmel**

### CODE REVIEW

**Comment by joshbrown-eg** [comment]
Looks good to me, and the tests pass.

**Review by joshuatbrown — APPROVED** [review]
Looks good to me, and the tests pass. This is what I expected.

**Comment by cpatterson-lilly** [comment]
If we're going down this path, we need to be complete, by adding a new `timeout:` version of *every* `RZBPeripheral` method that called the original `dispatchCommand(_:)`:
- `-readRSSI:`
- `-cancelConnectionWithCompletion:`
- `-connectWithCompletion:`
- `-readCharacteristicUUID:serviceUUID:completion:`
- `-enableNotifyForCharacteristicUUID:serviceUUID:onNotify:completion:`
- `-clearNotifyBlockForCharacteristicUUID:serviceUUID:completion:`
- `-writeData:characteristicUUID:serviceUUID:`
- `-writeData:characteristicUUID:serviceUUID:completion:`
- `-discoverServiceUUIDs:completion:`
- `-discoverCharacteristicUUIDs:serviceUUID:completion:`

**Review by mplorentz — APPROVED** [review]

**Comment by mattremmel** [comment]
@cpatterson-lilly these changes preserve the old behavior of all the old API's, so all the functions you mentioned will behave as they used to. The 3 functions that were updated with new API with timeout parameter were the API's that we called `LillyUserInteraction.setTimeout` before calling in LillyDevice. Those were updated so that we could provide the timeout that we wanted without changing the global state.

If you are wanting to update all those functions for the sake of completeness, thats fine, but I don't believe there are any places in LillyDevice where we modify the global timeout value before calling them, so they will continue to behave the same regardless. Is that what you are referring to?

**Comment by cpatterson-lilly** [comment]
Yes, I want to update them for the sake of completeness, because I want *every change* we make to RZBluetooth to be something capable of being merged back to the main repo.

**Comment by mattremmel** [comment]
Okay, sounds good. I can get that done today 👍

**Pull request closed without merging**
